{% set version = "1.0-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-matrixcalc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/matrixcalc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/matrixcalc/matrixcalc_{{ version }}.tar.gz
  sha256: 0bc7d2f11f62d8b1969474defe27c924a243ccba0c856d585f317f6caa07f326

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('matrixcalc')"           # [not win]
    - "\"%R%\" -e \"library('matrixcalc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=matrixcalc
  license: GPL-2.0-or-later
  summary: A collection of functions to support matrix calculations for probability, econometric and numerical analysis. There are additional functions that are comparable to APL functions which are useful for actuarial models such as pension mathematics. This package is used for teaching and research purposes at the Department
    of Finance and Risk Engineering, New York University, Polytechnic Institute, Brooklyn, NY 11201.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
